#!/usr/bin/env python3
"""
Generate subsetted VLW fonts (LovyanGFX/TFT_eSPI smooth-font format)
from a TTF and emit them as C headers for embedding in flash.

VLW layout (all int32 big-endian, matches lgfx::VLWfont::loadFont):
  header : count, version(11), size, pad, ascent, descent          (24 B)
  glyphs : unicode, height, width, xAdvance, topExtent, leftExtent,
           pad                                                     (28 B each)
  bitmaps: 8-bit alpha, width*height bytes per glyph, same order

Usage:  python3 make_vlw.py            (regenerates all fonts)
"""
import struct
import sys
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

HERE = Path(__file__).parent
TTF = HERE / "fonts" / "BarlowCondensed-Bold.ttf"
OUT_DIR = HERE.parent / "src" / "assets"

CHARSET_FULL = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ .:%/-!"
FONTS = [
    # (name, px size, charset)
    ("speed44", 44, "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ .:-"),
    ("hero30",  30, "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ .:-"),
    ("med20",   20, CHARSET_FULL),
    ("small12", 12, CHARSET_FULL),
]


def render_glyph(font, ch, ascent):
    """Return (bitmap bytes, w, h, xadv, top_extent, left_extent)."""
    pad = 16
    canvas = Image.new("L", (pad * 2 + 128, pad * 2 + 160), 0)
    ImageDraw.Draw(canvas).text((pad, pad), ch, font=font, fill=255)
    xadv = max(1, round(font.getlength(ch)))
    bbox = canvas.getbbox()
    if bbox is None:                      # space etc: no ink
        return b"", 0, 0, xadv, 0, 0
    x0, y0, x1, y1 = bbox
    w, h = x1 - x0, y1 - y0
    glyph = canvas.crop(bbox)
    left = x0 - pad                       # bearing from cursor
    top = ascent - (y0 - pad)             # rows above baseline
    return glyph.tobytes(), w, h, xadv, top, left


def build_vlw(ttf, size, charset):
    font = ImageFont.truetype(str(ttf), size)
    ascent, descent = font.getmetrics()
    # LovyanGFX looks glyphs up with std::lower_bound (binary search):
    # the table MUST be sorted by codepoint or every lookup fails and
    # each char renders as the hollow missing-glyph box.
    charset = sorted(set(charset), key=ord)
    glyphs = [(ord(c),) + render_glyph(font, c, ascent) for c in charset]

    out = bytearray()
    out += struct.pack(">6i", len(glyphs), 11, size, 0, ascent, descent)
    for code, _bmp, w, h, xadv, top, left in glyphs:
        out += struct.pack(">7i", code, h, w, xadv, top, left, 0)
    for _code, bmp, *_rest in glyphs:
        out += bmp
    widths = {chr(c): x for c, _b, _w, _h, x, _t, _l in glyphs}
    return bytes(out), ascent, descent, widths


def emit_header(name, blob):
    guard = f"FONT_{name.upper()}_H"
    lines = [
        "// Auto-generated by tools/make_vlw.py — do not edit.",
        f"// VLW font '{name}' from Barlow Condensed Bold (OFL).",
        f"// {len(blob)} bytes, lives in flash (.rodata).",
        "#pragma once",
        "#include <stdint.h>",
        "",
        f"alignas(4) static constexpr uint8_t font_{name}_vlw[] = {{",
    ]
    for i in range(0, len(blob), 16):
        chunk = ", ".join(f"0x{b:02X}" for b in blob[i:i + 16])
        lines.append(f"    {chunk},")
    lines += ["};", ""]
    (OUT_DIR / f"font_{name}.h").write_text("\n".join(lines))


def main():
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    total = 0
    for name, size, charset in FONTS:
        blob, ascent, descent, widths = build_vlw(TTF, size, charset)
        emit_header(name, blob)
        total += len(blob)
        sample = "".join(c for c in "12.05" if c in widths)
        w1205 = sum(widths.get(c, 0) for c in "12.05")
        print(f"{name:8s} size={size:2d}px ascent={ascent} descent={descent} "
              f"glyphs={len(charset)} bytes={len(blob):6d} width('12.05')={w1205}px")
    print(f"TOTAL: {total} bytes of flash")


if __name__ == "__main__":
    sys.exit(main())
